name: Licenses
description: Run licenses check

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Build packages
      run: npm run build:packages
      shell: bash

    - name: Licenses check
      run: npx @cloud-ru/ft-license-validator
      shell: bash
