function getRawCommit() {
  return {
    type: 'feat',
    scope: 'FF-1505',
    breakingMark: '!',
    subject: 'some breaking changes',
    merge: null,
    header: 'feat(FF-1505)!: some breaking changes',
    body: null,
    footer: null,
    notes: [
      {
        title: 'BREAKING CHANGE',
        text: 'some breaking changes',
      },
    ],
    references: [],
    mentions: [],
    revert: null,
    hash: '49178dcac414bfa34b08d8f94feea73e953393ea',
    gitTags: ' (HEAD -> master)',
    committerDate: '2023-01-12',
  };
}

function getContext() {
  const breakingChangesCommit = {
    type: 'Features',
    scope: 'FF-1505',
    breakingMark: '!',
    subject: 'some breaking changes',
    merge: null,
    header: 'feat(FF-1505)!: some breaking changes',
    body: null,
    footer: null,
    notes: [
      {
        title: 'BREAKING CHANGES',
        text: 'some breaking changes',
        commit: 'link to commit object',
      },
    ],
    references: [],
    mentions: [],
    revert: null,
    hash: '49178dcac414bfa34b08d8f94feea73e953393ea',
    gitTags: '',
    committerDate: '2023-01-12',
    shortHash: '49178dc',
    raw: {
      type: 'feat',
      scope: 'FF-1505',
      breakingMark: '!',
      subject: 'some breaking changes',
      merge: null,
      header: 'feat(FF-1505)!: some breaking changes',
      body: null,
      footer: null,
      notes: [
        {
          title: 'BREAKING CHANGE',
          text: 'some breaking changes',
        },
      ],
      references: [],
      mentions: [],
      revert: null,
      hash: '49178dcac414bfa34b08d8f94feea73e953393ea',
      gitTags: '',
      committerDate: '2023-01-12',
    },
  };

  breakingChangesCommit.notes[0].commit = breakingChangesCommit;

  return {
    commit: 'commits',
    issue: 'issues',
    date: '2023-01-13',
    version: '4.0.0',
    host: 'https://github.com/cloud-ru-tech/frontend-tools',
    owner: 'cloud-ru-ui',
    repository: 'uikit-product',
    repoUrl: 'https://github.com/cloud-ru-tech/frontend-tools',
    packageData: {
      name: '@cloud-ru/uikit-checkbox',
      title: 'React Checkbox',
      version: '4.0.0',
      sideEffects: ['*.css', '*.woff', '*.woff2'],
      description: '',
      main: './dist/esm/index.js',
      module: './dist/esm/index.js',
      homepage: 'https://github.com/cloud-ru-tech/frontend-tools',
      repository: {
        type: 'git',
        url: 'https://github.com/cloud-ru-tech/frontend-tools.git',
        directory: 'packages/checkbox',
      },
      files: ['dist', 'src'],
      license: 'UNLICENSED',
      scripts: {},
      dependencies: {
        '@cloud-ru/uikit-icons': '5.5.0',
        '@cloud-ru/uikit-theme': '0.35.1',
        '@cloud-ru/uikit-typography': '1.3.0',
        '@cloud-ru/uikit-utils': '3.1.1',
      },
      readme: 'ERROR: No README data found!',
      _id: '@cloud-ru/uikit-checkbox@4.0.0',
    },
    gitSemverTags: [
      '@cloud-ru/uikit-checkbox@3.1.4',
      '@cloud-ru/uikit-checkbox@3.1.3',
      '@cloud-ru/uikit-checkbox@3.1.2',
      '@cloud-ru/uikit-checkbox@3.1.1',
      '@cloud-ru/uikit-checkbox@3.1.0',
      '@cloud-ru/uikit-checkbox@3.0.38',
      '@cloud-ru/uikit-checkbox@3.0.37',
      '@cloud-ru/uikit-checkbox@3.0.36',
      '@cloud-ru/uikit-checkbox@3.0.35',
      '@cloud-ru/uikit-checkbox@3.0.34',
      '@cloud-ru/uikit-checkbox@3.0.33',
      '@cloud-ru/uikit-checkbox@3.0.32',
      '@cloud-ru/uikit-checkbox@3.0.31',
      '@cloud-ru/uikit-checkbox@3.0.30',
      '@cloud-ru/uikit-checkbox@3.0.29',
      '@cloud-ru/uikit-checkbox@3.0.28',
      '@cloud-ru/uikit-checkbox@3.0.27',
      '@cloud-ru/uikit-checkbox@3.0.26',
      '@cloud-ru/uikit-checkbox@3.0.25',
      '@cloud-ru/uikit-checkbox@3.0.24',
      '@cloud-ru/uikit-checkbox@3.0.23',
      '@cloud-ru/uikit-checkbox@3.0.22',
      '@cloud-ru/uikit-checkbox@3.0.21',
      '@cloud-ru/uikit-checkbox@3.0.20',
      '@cloud-ru/uikit-checkbox@3.0.19',
      '@cloud-ru/uikit-checkbox@3.0.18',
      '@cloud-ru/uikit-checkbox@3.0.17',
      '@cloud-ru/uikit-checkbox@3.0.16',
    ],
    linkReferences: true,
    commitGroups: [
      {
        title: 'Bug Fixes',
        commits: [
          {
            type: 'Bug Fixes',
            scope: 'FF-1505',
            breakingMark: null,
            subject: 'add some fix here',
            merge: null,
            header: 'fix(FF-1505): add some fix here',
            body: null,
            footer: null,
            notes: [],
            references: [],
            mentions: [],
            revert: null,
            hash: '4a990ac789586f469419861e2819e6e0e57d39d9',
            gitTags: '',
            committerDate: '2023-01-13',
            shortHash: '4a990ac',
            raw: {
              type: 'fix',
              scope: 'FF-1505',
              breakingMark: null,
              subject: 'add some fix here',
              merge: null,
              header: 'fix(FF-1505): add some fix here',
              body: null,
              footer: null,
              notes: [],
              references: [],
              mentions: [],
              revert: null,
              hash: '4a990ac789586f469419861e2819e6e0e57d39d9',
              gitTags: '',
              committerDate: '2023-01-13',
            },
          },
        ],
      },
      {
        title: 'Features',
        commits: [
          {
            type: 'Features',
            scope: 'FF-1505',
            breakingMark: null,
            subject: 'add some another feature',
            merge: null,
            header: 'feat(FF-1505): add some another feature',
            body: null,
            footer: null,
            notes: [],
            references: [],
            mentions: [],
            revert: null,
            hash: 'a04e9a72abb39f0836981e1ad6c4b3ca3a845714',
            gitTags: ' (HEAD -> master)',
            committerDate: '2023-01-13',
            shortHash: 'a04e9a7',
            raw: {
              type: 'feat',
              scope: 'FF-1505',
              breakingMark: null,
              subject: 'add some another feature',
              merge: null,
              header: 'feat(FF-1505): add some another feature',
              body: null,
              footer: null,
              notes: [],
              references: [],
              mentions: [],
              revert: null,
              hash: 'a04e9a72abb39f0836981e1ad6c4b3ca3a845714',
              gitTags: ' (HEAD -> master)',
              committerDate: '2023-01-13',
            },
          },
          breakingChangesCommit,
        ],
      },
    ],
    noteGroups: [
      {
        title: 'BREAKING CHANGES',
        notes: [
          {
            title: 'BREAKING CHANGES',
            text: 'some breaking changes',
            commit: breakingChangesCommit,
          },
        ],
      },
    ],
    isPatch: false,
  };
}

module.exports = {
  getRawCommit,
  getContext,
};
